import type { Metadata } from "next";
import { Inter, Sacramento } from "next/font/google";
import "./globals.css";
import Bg from "@/components/bg/Bg";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const sacramento = Sacramento({ weight: "400", subsets: ["latin"], variable: "--font-sacramento" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sacramento.variable} text-primary`}>
        <Bg />
        <main className="w-screen h-screen">{children}</main>
      </body>
    </html>
  );
}
